### ISSUE TITLE
The invalid value entered for the menu , makes it an infinite loop

### ISSUE THREAD

**Issue by dheerajalim** [tecladocode/complete-python-course#2]
[https://github.com/tecladocode/complete-python-course/blob/master/section3/milestone_1/app.py]
Once you start the program, the program asks for user input. 
The invalid input is not handled correctly.

Enter 'a' to add a movie, 'l' to see your movies, 'f' to find a movie, and 'q' to quit: <enter anything apart from a,I,f,q>

and then see the infinite loop

Unknown command-please try again.
Unknown command-please try again.
Unknown command-please try again.
Unknown command-please try again.
Unknown command-please try again...............

**Comment by jslvtr** [comment]
Thank you @dheerajalim ! We will fix this—I think the `continue` statement there is the cause of this bug.

**Comment by dheerajalim** [comment]
Yes @jslvtr , that is the issue. Thanks for taking up the defect
