### ISSUE TITLE
Json file will be replaced at each start

### ISSUE THREAD

**Issue by ruky87** [tecladocode/complete-python-course#3]
Milestone Project 2 with JSON
File is:  complete-python-course/section7/milestone_2_json/utils/database.py
If you create an empty database (file in write mode) the old database gets replaced every time you start the app. You should check if file exists or manage the error when trying to load an empty json file, creating here the empty list in the file.

**Comment by jslvtr** [comment]
Hey @ruky87 that's intended functionality. Creating a new database will delete the old one in this program!
